export { default as HeroSection } from './HeroSection'
export { default as ProjectsSection } from './ProjectsSection'
export { default as AchievementSection } from './AchievementSection'
export { default as EducationSection } from './EducationSection'
export { default as ContactSection } from './ContactSection'
